docs: update CHANGELOG for Kamakura
edgexfoundry/device-snmp-go pull request #168
Opened 2022-05-08 00:00 UTC by jpwhitemn

Also provide Jakarta changelog

Signed-off-by: jpwhitemn <jpwhite_mn@yahoo.com>

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-snmp-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2022-05-10 06:35 UTC, cloudxxx8 requested changes

2022-05-10 06:35 UTC, cloudxxx8 commented on CHANGELOG.md
> +### Bug Fixes ðŸ›
duplicated bug fixes section, and the icon is wrong

2022-05-11 16:12 UTC, cloudxxx8 commented on CHANGELOG.md
> +## [v2.0.0] Kamakura - 2022-05-11  (Not Compatible with 1.x releases)
it's v2.2.0

2022-05-12 00:05 UTC, iain-anderson approved these changes

2022-05-12 05:41 UTC, cloudxxx8 approved these changes
LGTM

2022-05-12 05:42 UTC, merged